import { StyleSheet } from "react-native";

export const dashboardStyles = StyleSheet.create({
  container: {
    flex: 1,
  },
  background: {
    flex: 1,
  },
  safeArea: {
    flex: 1,
  },
  content: {
    padding: 20,
    paddingBottom: 40,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  menuButton: {
    padding: 8,
  },
  greetingContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  greeting: {
    color: "#1a202c",
    fontSize: 18,
    fontWeight: "800",
  },
  tagline: {
    color: "#4a5568",
    fontSize: 16,
    fontWeight: "500",
  },
  profileContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  profileImageWrapper: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "#edf2f7",
    justifyContent: "center",
    alignItems: "center",
    overflow: "hidden",
    borderWidth: 2,
    borderColor: "#e2e8f0",
  },
  profileImage: {
    width: 44,
    height: 44,
    borderRadius: 22,
  },
  weatherSection: {
    marginBottom: 24,
    borderRadius: 12,
    overflow: "hidden",
    backgroundColor: "#ffffff",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 3,
  },
  favoritesSection: {
    marginTop: 24,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 4,
  },
  heading: {
    fontSize: 20,
    fontWeight: "700",
    color: "#1a202c",
    marginLeft: 8,
  },
  favoritesScroll: {
    marginTop: 8,
    paddingLeft: 4,
  },
  card: {
    width: 280,
    marginRight: 16,
    borderRadius: 16,
    backgroundColor: "#ffffff",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
    overflow: "hidden",
  },
  cardContent: {
    padding: 16,
  },
  cardHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  spotTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#1a202c",
    marginLeft: 8,
  },
  imageContainer: {
    position: "relative",
    borderRadius: 12,
    overflow: "hidden",
    marginBottom: 12,
  },
  image: {
    width: "100%",
    height: 160,
  },
  imageGradient: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: 60,
  },
  weatherInfo: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
    backgroundColor: "#f8fafc",
    padding: 8,
    borderRadius: 8,
  },
  weather: {
    fontSize: 14,
    color: "#4a5568",
    marginLeft: 8,
    flex: 1,
  },
  goFishContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 8,
    marginBottom: 12,
    padding: 8,
    borderRadius: 8,
    backgroundColor: "#f0fff4",
  },
  goFish: {
    fontSize: 14,
    fontWeight: "600",
    color: "#38a169",
    marginLeft: 8,
  },
  cardFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: "#edf2f7",
  },
  updatedContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  updatedText: {
    fontSize: 12,
    color: "#718096",
    marginLeft: 4,
  },
  loadingContainer: {
    alignItems: "center",
    justifyContent: "center",
    padding: 40,
    backgroundColor: "#ffffff",
    borderRadius: 12,
  },
  loadingText: {
    color: "#4a5568",
    marginTop: 12,
    fontSize: 14,
  },
  emptyState: {
    padding: 40,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#ffffff",
    borderRadius: 12,
  },
  emptyStateText: {
    color: "#4a5568",
    fontSize: 14,
    textAlign: "center",
    marginTop: 12,
  },
  tripBanner: {
    marginBottom: 24,
    borderRadius: 12,
    backgroundColor: "#ebf8ff",
    padding: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 3,
  },
  tripBannerContent: {
    alignItems: "center",
  },
  tripText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#2b6cb0",
    textAlign: "center",
    marginBottom: 4,
  },
  tripSubtext: {
    fontSize: 14,
    color: "#4a5568",
    textAlign: "center",
    marginBottom: 8,
  },
  stopTripButton: {
    marginTop: 8,
    backgroundColor: "#fff5f5",
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 20,
  },
  stopTripButtonText: {
    color: "#c53030",
    fontWeight: "600",
  },
  startFishingButton: {
    marginBottom: 24,
    backgroundColor: "#ffffff",
    padding: 16,
    borderRadius: 12,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 3,
  },
  startFishingText: {
    color: "#2d3748",
    fontSize: 16,
    fontWeight: "600",
  },
  placeholderContainer: {
    width: "100%",
    height: 200,
    borderRadius: 12,
    backgroundColor: "#e0e0e0",
    justifyContent: "center",
    alignItems: "center",
  },
  placeholderText: {
    color: "#888",
    fontSize: 16,
  },
});
