const problemsData = {
  "Arrays & Hashing": [
    {
      title: "1. Two Sum",
      link: "https://leetcode.com/problems/two-sum",
      frequency: "100.00%",
      difficulty: "Easy",
    },
    {
      title: "4. Median of Two Sorted Arrays",
      link: "https://leetcode.com/problems/median-of-two-sorted-arrays",
      frequency: "93.49%",
      difficulty: "Hard",
    },
    {
      title: "11. Container With Most Water",
      link: "https://leetcode.com/problems/container-with-most-water",
      frequency: "85.14%",
      difficulty: "Medium",
    },
    {
      title: "15. 3Sum",
      link: "https://leetcode.com/problems/3sum",
      frequency: "87.01%",
      difficulty: "Medium",
    },
    {
      title: "16. 3Sum Closest",
      link: "https://leetcode.com/problems/3sum-closest",
      frequency: "69.30%",
      difficulty: "Medium",
    },
    {
      title: "18. 4Sum",
      link: "https://leetcode.com/problems/4sum",
      frequency: "79.09%",
      difficulty: "Medium",
    },
    {
      title: "26. Remove Duplicates from Sorted Array",
      link: "https://leetcode.com/problems/remove-duplicates-from-sorted-array",
      frequency: "82.12%",
      difficulty: "Easy",
    },
    {
      title: "27. Remove Element",
      link: "https://leetcode.com/problems/remove-element",
      frequency: "75.72%",
      difficulty: "Easy",
    },
    {
      title: "31. Next Permutation",
      link: "https://leetcode.com/problems/next-permutation",
      frequency: "83.63%",
      difficulty: "Medium",
    },
    {
      title: "33. Search in Rotated Sorted Array",
      link: "https://leetcode.com/problems/search-in-rotated-sorted-array",
      frequency: "80.56%",
      difficulty: "Medium",
    },
    {
      title: "34. Find First and Last Position of Element in Sorted Array",
      link: "https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array",
      frequency: "80.81%",
      difficulty: "Medium",
    },
    {
      title: "35. Search Insert Position",
      link: "https://leetcode.com/problems/search-insert-position",
      frequency: "72.10%",
      difficulty: "Easy",
    },
    {
      title: "36. Valid Sudoku",
      link: "https://leetcode.com/problems/valid-sudoku",
      frequency: "74.80%",
      difficulty: "Medium",
    },
    {
      title: "37. Sudoku Solver",
      link: "https://leetcode.com/problems/sudoku-solver",
      frequency: "72.80%",
      difficulty: "Hard",
    },
    {
      title: "39. Combination Sum",
      link: "https://leetcode.com/problems/combination-sum",
      frequency: "72.99%",
      difficulty: "Medium",
    },
    {
      title: "40. Combination Sum II",
      link: "https://leetcode.com/problems/combination-sum-ii",
      frequency: "59.13%",
      difficulty: "Medium",
    },
    {
      title: "41. First Missing Positive",
      link: "https://leetcode.com/problems/first-missing-positive",
      frequency: "80.22%",
      difficulty: "Hard",
    },
    {
      title: "42. Trapping Rain Water",
      link: "https://leetcode.com/problems/trapping-rain-water",
      frequency: "96.67%",
      difficulty: "Hard",
    },
    {
      title: "45. Jump Game II",
      link: "https://leetcode.com/problems/jump-game-ii",
      frequency: "74.61%",
      difficulty: "Medium",
    },
    {
      title: "46. Permutations",
      link: "https://leetcode.com/problems/permutations",
      frequency: "74.66%",
      difficulty: "Medium",
    },
    {
      title: "47. Permutations II",
      link: "https://leetcode.com/problems/permutations-ii",
      frequency: "57.97%",
      difficulty: "Medium",
    },
    {
      title: "48. Rotate Image",
      link: "https://leetcode.com/problems/rotate-image",
      frequency: "84.64%",
      difficulty: "Medium",
    },
    {
      title: "49. Group Anagrams",
      link: "https://leetcode.com/problems/group-anagrams",
      frequency: "89.25%",
      difficulty: "Medium",
    },
    {
      title: "51. N-Queens",
      link: "https://leetcode.com/problems/n-queens",
      frequency: "81.85%",
      difficulty: "Hard",
    },
    {
      title: "53. Maximum Subarray",
      link: "https://leetcode.com/problems/maximum-subarray",
      frequency: "86.77%",
      difficulty: "Medium",
    },
    {
      title: "54. Spiral Matrix",
      link: "https://leetcode.com/problems/spiral-matrix",
      frequency: "87.62%",
      difficulty: "Medium",
    },
    {
      title: "55. Jump Game",
      link: "https://leetcode.com/problems/jump-game",
      frequency: "82.18%",
      difficulty: "Medium",
    },
    {
      title: "56. Merge Intervals",
      link: "https://leetcode.com/problems/merge-intervals",
      frequency: "95.39%",
      difficulty: "Medium",
    },
    {
      title: "57. Insert Interval",
      link: "https://leetcode.com/problems/insert-interval",
      frequency: "62.95%",
      difficulty: "Medium",
    },
    {
      title: "59. Spiral Matrix II",
      link: "https://leetcode.com/problems/spiral-matrix-ii",
      frequency: "63.31%",
      difficulty: "Medium",
    },
    {
      title: "63. Unique Paths II",
      link: "https://leetcode.com/problems/unique-paths-ii",
      frequency: "58.24%",
      difficulty: "Medium",
    },
    {
      title: "64. Minimum Path Sum",
      link: "https://leetcode.com/problems/minimum-path-sum",
      frequency: "66.41%",
      difficulty: "Medium",
    },
    {
      title: "66. Plus One",
      link: "https://leetcode.com/problems/plus-one",
      frequency: "72.72%",
      difficulty: "Easy",
    },
    {
      title: "68. Text Justification",
      link: "https://leetcode.com/problems/text-justification",
      frequency: "87.40%",
      difficulty: "Hard",
    },
    {
      title: "73. Set Matrix Zeroes",
      link: "https://leetcode.com/problems/set-matrix-zeroes",
      frequency: "68.52%",
      difficulty: "Medium",
    },
    {
      title: "74. Search a 2D Matrix",
      link: "https://leetcode.com/problems/search-a-2d-matrix",
      frequency: "68.93%",
      difficulty: "Medium",
    },
    {
      title: "75. Sort Colors",
      link: "https://leetcode.com/problems/sort-colors",
      frequency: "76.25%",
      difficulty: "Medium",
    },
    {
      title: "78. Subsets",
      link: "https://leetcode.com/problems/subsets",
      frequency: "76.58%",
      difficulty: "Medium",
    },
    {
      title: "79. Word Search",
      link: "https://leetcode.com/problems/word-search",
      frequency: "80.24%",
      difficulty: "Medium",
    },
    {
      title: "80. Remove Duplicates from Sorted Array II",
      link: "https://leetcode.com/problems/remove-duplicates-from-sorted-array-ii",
      frequency: "64.39%",
      difficulty: "Medium",
    },
    {
      title: "81. Search in Rotated Sorted Array II",
      link: "https://leetcode.com/problems/search-in-rotated-sorted-array-ii",
      frequency: "54.41%",
      difficulty: "Medium",
    },
    {
      title: "84. Largest Rectangle in Histogram",
      link: "https://leetcode.com/problems/largest-rectangle-in-histogram",
      frequency: "77.00%",
      difficulty: "Hard",
    },
    {
      title: "85. Maximal Rectangle",
      link: "https://leetcode.com/problems/maximal-rectangle",
      frequency: "71.52%",
      difficulty: "Hard",
    },
    {
      title: "88. Merge Sorted Array",
      link: "https://leetcode.com/problems/merge-sorted-array",
      frequency: "97.96%",
      difficulty: "Easy",
    },
    {
      title: "90. Subsets II",
      link: "https://leetcode.com/problems/subsets-ii",
      frequency: "59.44%",
      difficulty: "Medium",
    },
    {
      title: "105. Construct Binary Tree from Preorder and Inorder Traversal",
      link: "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal",
      frequency: "59.86%",
      difficulty: "Medium",
    },
    {
      title: "106. Construct Binary Tree from Inorder and Postorder Traversal",
      link: "https://leetcode.com/problems/construct-binary-tree-from-inorder-and-postorder-traversal",
      frequency: "32.68%",
      difficulty: "Medium",
    },
    {
      title: "108. Convert Sorted Array to Binary Search Tree",
      link: "https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree",
      frequency: "58.05%",
      difficulty: "Easy",
    },
    {
      title: "118. Pascal's Triangle",
      link: "https://leetcode.com/problems/pascals-triangle",
      frequency: "79.77%",
      difficulty: "Easy",
    },
    {
      title: "119. Pascal's Triangle II",
      link: "https://leetcode.com/problems/pascals-triangle-ii",
      frequency: "43.46%",
      difficulty: "Easy",
    },
  ],
  "Two Pointers": [
    {
      title: "5. Longest Palindromic Substring",
      link: "https://leetcode.com/problems/longest-palindromic-substring",
      frequency: "93.70%",
      difficulty: "Medium",
    },
    {
      title: "11. Container With Most Water",
      link: "https://leetcode.com/problems/container-with-most-water",
      frequency: "85.14%",
      difficulty: "Medium",
    },
    {
      title: "15. 3Sum",
      link: "https://leetcode.com/problems/3sum",
      frequency: "87.01%",
      difficulty: "Medium",
    },
    {
      title: "16. 3Sum Closest",
      link: "https://leetcode.com/problems/3sum-closest",
      frequency: "69.30%",
      difficulty: "Medium",
    },
    {
      title: "18. 4Sum",
      link: "https://leetcode.com/problems/4sum",
      frequency: "79.09%",
      difficulty: "Medium",
    },
    {
      title: "19. Remove Nth Node From End of List",
      link: "https://leetcode.com/problems/remove-nth-node-from-end-of-list",
      frequency: "71.10%",
      difficulty: "Medium",
    },
    {
      title: "26. Remove Duplicates from Sorted Array",
      link: "https://leetcode.com/problems/remove-duplicates-from-sorted-array",
      frequency: "82.12%",
      difficulty: "Easy",
    },
    {
      title: "27. Remove Element",
      link: "https://leetcode.com/problems/remove-element",
      frequency: "75.72%",
      difficulty: "Easy",
    },
    {
      title: "28. Find the Index of the First Occurrence in a String",
      link: "https://leetcode.com/problems/find-the-index-of-the-first-occurrence-in-a-string",
      frequency: "74.62%",
      difficulty: "Easy",
    },
    {
      title: "31. Next Permutation",
      link: "https://leetcode.com/problems/next-permutation",
      frequency: "83.63%",
      difficulty: "Medium",
    },
    {
      title: "42. Trapping Rain Water",
      link: "https://leetcode.com/problems/trapping-rain-water",
      frequency: "96.67%",
      difficulty: "Hard",
    },
    {
      title: "61. Rotate List",
      link: "https://leetcode.com/problems/rotate-list",
      frequency: "64.11%",
      difficulty: "Medium",
    },
    {
      title: "75. Sort Colors",
      link: "https://leetcode.com/problems/sort-colors",
      frequency: "76.25%",
      difficulty: "Medium",
    },
    {
      title: "80. Remove Duplicates from Sorted Array II",
      link: "https://leetcode.com/problems/remove-duplicates-from-sorted-array-ii",
      frequency: "64.39%",
      difficulty: "Medium",
    },
    {
      title: "82. Remove Duplicates from Sorted List II",
      link: "https://leetcode.com/problems/remove-duplicates-from-sorted-list-ii",
      frequency: "50.31%",
      difficulty: "Medium",
    },
    {
      title: "86. Partition List",
      link: "https://leetcode.com/problems/partition-list",
      frequency: "60.41%",
      difficulty: "Medium",
    },
    {
      title: "88. Merge Sorted Array",
      link: "https://leetcode.com/problems/merge-sorted-array",
      frequency: "97.96%",
      difficulty: "Easy",
    },
    {
      title: "125. Valid Palindrome",
      link: "https://leetcode.com/problems/valid-palindrome",
      frequency: "82.57%",
      difficulty: "Easy",
    },
    {
      title: "141. Linked List Cycle",
      link: "https://leetcode.com/problems/linked-list-cycle",
      frequency: "63.40%",
      difficulty: "Easy",
    },
    {
      title: "142. Linked List Cycle II",
      link: "https://leetcode.com/problems/linked-list-cycle-ii",
      frequency: "54.42%",
      difficulty: "Medium",
    },
    {
      title: "143. Reorder List",
      link: "https://leetcode.com/problems/reorder-list",
      frequency: "71.51%",
      difficulty: "Medium",
    },
    {
      title: "148. Sort List",
      link: "https://leetcode.com/problems/sort-list",
      frequency: "60.75%",
      difficulty: "Medium",
    },
    {
      title: "151. Reverse Words in a String",
      link: "https://leetcode.com/problems/reverse-words-in-a-string",
      frequency: "74.82%",
      difficulty: "Medium",
    },
    {
      title: "160. Intersection of Two Linked Lists",
      link: "https://leetcode.com/problems/intersection-of-two-linked-lists",
      frequency: "61.30%",
      difficulty: "Easy",
    },
    {
      title: "161. One Edit Distance",
      link: "https://leetcode.com/problems/one-edit-distance",
      frequency: "56.67%",
      difficulty: "Medium",
    },
    {
      title: "165. Compare Version Numbers",
      link: "https://leetcode.com/problems/compare-version-numbers",
      frequency: "65.21%",
      difficulty: "Medium",
    },
    {
      title: "167. Two Sum II - Input Array Is Sorted",
      link: "https://leetcode.com/problems/two-sum-ii-input-array-is-sorted",
      frequency: "70.01%",
      difficulty: "Medium",
    },
    {
      title: "170. Two Sum III - Data structure design",
      link: "https://leetcode.com/problems/two-sum-iii-data-structure-design",
      frequency: "26.82%",
      difficulty: "Easy",
    },
    {
      title: "186. Reverse Words in a String II",
      link: "https://leetcode.com/problems/reverse-words-in-a-string-ii",
      frequency: "0.00%",
      difficulty: "Medium",
    },
    {
      title: "189. Rotate Array",
      link: "https://leetcode.com/problems/rotate-array",
      frequency: "78.42%",
      difficulty: "Medium",
    },
    {
      title: "202. Happy Number",
      link: "https://leetcode.com/problems/happy-number",
      frequency: "78.76%",
      difficulty: "Easy",
    },
    {
      title: "234. Palindrome Linked List",
      link: "https://leetcode.com/problems/palindrome-linked-list",
      frequency: "72.28%",
      difficulty: "Easy",
    },
    {
      title: "244. Shortest Word Distance II",
      link: "https://leetcode.com/problems/shortest-word-distance-ii",
      frequency: "69.00%",
      difficulty: "Medium",
    },
    {
      title: "246. Strobogrammatic Number",
      link: "https://leetcode.com/problems/strobogrammatic-number",
      frequency: "54.35%",
      difficulty: "Easy",
    },
    {
      title: "251. Flatten 2D Vector",
      link: "https://leetcode.com/problems/flatten-2d-vector",
      frequency: "59.75%",
      difficulty: "Medium",
    },
    {
      title: "253. Meeting Rooms II",
      link: "https://leetcode.com/problems/meeting-rooms-ii",
      frequency: "89.90%",
      difficulty: "Medium",
    },
    {
      title: "259. 3Sum Smaller",
      link: "https://leetcode.com/problems/3sum-smaller",
      frequency: "58.54%",
      difficulty: "Medium",
    },
    {
      title: "272. Closest Binary Search Tree Value II",
      link: "https://leetcode.com/problems/closest-binary-search-tree-value-ii",
      frequency: "33.61%",
      difficulty: "Hard",
    },
    {
      title: "277. Find the Celebrity",
      link: "https://leetcode.com/problems/find-the-celebrity",
      frequency: "71.65%",
      difficulty: "Medium",
    },
    {
      title: "283. Move Zeroes",
      link: "https://leetcode.com/problems/move-zeroes",
      frequency: "79.16%",
      difficulty: "Easy",
    },
    {
      title: "287. Find the Duplicate Number",
      link: "https://leetcode.com/problems/find-the-duplicate-number",
      frequency: "69.44%",
      difficulty: "Medium",
    },
    {
      title: "295. Find Median from Data Stream",
      link: "https://leetcode.com/problems/find-median-from-data-stream",
      frequency: "83.26%",
      difficulty: "Hard",
    },
    {
      title: "321. Create Maximum Number",
      link: "https://leetcode.com/problems/create-maximum-number",
      frequency: "47.70%",
      difficulty: "Hard",
    },
    {
      title: "344. Reverse String",
      link: "https://leetcode.com/problems/reverse-string",
      frequency: "65.97%",
      difficulty: "Easy",
    },
    {
      title: "345. Reverse Vowels of a String",
      link: "https://leetcode.com/problems/reverse-vowels-of-a-string",
      frequency: "65.33%",
      difficulty: "Easy",
    },
    {
      title: "349. Intersection of Two Arrays",
      link: "https://leetcode.com/problems/intersection-of-two-arrays",
      frequency: "73.32%",
      difficulty: "Easy",
    },
    {
      title: "350. Intersection of Two Arrays II",
      link: "https://leetcode.com/problems/intersection-of-two-arrays-ii",
      frequency: "58.90%",
      difficulty: "Easy",
    },
    {
      title: "360. Sort Transformed Array",
      link: "https://leetcode.com/problems/sort-transformed-array",
      frequency: "62.76%",
      difficulty: "Medium",
    },
    {
      title: "392. Is Subsequence",
      link: "https://leetcode.com/problems/is-subsequence",
      frequency: "68.34%",
      difficulty: "Easy",
    },
    {
      title: "408. Valid Word Abbreviation",
      link: "https://leetcode.com/problems/valid-word-abbreviation",
      frequency: "95.03%",
      difficulty: "Easy",
    },
  ],
  Stack: [
    {
      title: "Valid Parentheses",
      link: "https://leetcode.com/problems/valid-parentheses/",
    },
    { title: "Min Stack", link: "https://leetcode.com/problems/min-stack/" },
  ],
};

export default problemsData;
